"use client";

import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { useEffect, useState } from "react";
import { apiClient } from "@/lib/api/client";

export function PasswordSetupPage({ purpose }: { purpose:"INVITATION"|"PASSWORD_RESET" }) {
  const token = useSearchParams().get("token") || "";
  const [valid,setValid]=useState<boolean|null>(null), [email,setEmail]=useState(""), [password,setPassword]=useState(""), [confirm,setConfirm]=useState(""), [show,setShow]=useState(false), [error,setError]=useState(""), [done,setDone]=useState(false), [busy,setBusy]=useState(false);
  useEffect(()=>{ if(!token){setValid(false);return;} apiClient<{email:string}>(`/api/auth/password-token/validate?token=${encodeURIComponent(token)}&purpose=${purpose}`).then(r=>{setEmail(r.email);setValid(true)}).catch(()=>setValid(false)); },[token,purpose]);
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setError("");if(password!==confirm){setError("Passwords do not match.");return;}if(password.length<12){setError("Use at least 12 characters.");return;}setBusy(true);try{await apiClient(purpose==="INVITATION"?"/api/auth/accept-invitation":"/api/auth/reset-password",{method:"POST",body:JSON.stringify({token,newPassword:password,confirmPassword:confirm})});setDone(true);}catch(e:any){setError(e.message)}finally{setBusy(false)}};
  return <main className="grid min-h-screen place-items-center bg-[#f5f0e8] p-5" style={{fontFamily:"Arial, sans-serif"}}><section className="w-full max-w-md rounded-2xl border border-[#ddcfc1] bg-white p-7 shadow-xl sm:p-9"><p className="text-center font-serif text-sm tracking-[.28em] text-[#2c1810]">AH BRAIDING</p>{valid===null?<p className="mt-8 text-center text-neutral-500">Checking your secure link…</p>:!valid?<div className="mt-8 text-center"><h1 className="font-serif text-3xl text-[#2c1810]">This link has expired</h1><p className="mt-3 text-sm text-neutral-600">Request a new invitation or password-reset email.</p><Link className="mt-6 inline-block underline" href="/admin">Return to sign in</Link></div>:done?<div className="mt-8 text-center"><h1 className="font-serif text-3xl text-[#2c1810]">Password created</h1><p className="mt-3 text-sm text-neutral-600">Your administrator account is ready.</p><Link className="mt-6 inline-flex h-11 items-center rounded-md bg-[#2c1810] px-6 text-sm text-white" href="/admin">Continue to sign in</Link></div>:<><div className="mt-7 text-center"><h1 className="font-serif text-4xl text-[#2c1810]">{purpose==="INVITATION"?"Create your password":"Reset your password"}</h1><p className="mt-2 text-sm text-neutral-600">{email}</p></div>{error&&<p role="alert" className="mt-5 rounded-md bg-red-50 p-3 text-sm text-red-700">{error}</p>}<form onSubmit={submit} className="mt-6 space-y-4"><label className="block text-sm font-medium">New password<span className="relative mt-2 block"><input autoComplete="new-password" type={show?"text":"password"} value={password} onChange={e=>setPassword(e.target.value)} className="h-12 w-full rounded-md border px-4 pr-16"/><button type="button" onClick={()=>setShow(!show)} className="absolute right-2 top-1 h-10 px-2 text-sm">{show?"Hide":"Show"}</button></span></label><label className="block text-sm font-medium">Confirm password<input autoComplete="new-password" type={show?"text":"password"} value={confirm} onChange={e=>setConfirm(e.target.value)} className="mt-2 h-12 w-full rounded-md border px-4"/></label><p className="text-xs text-neutral-500">Use at least 12 characters. A memorable passphrase works well.</p><button disabled={busy} className="h-12 w-full rounded-md bg-[#2c1810] text-sm font-semibold tracking-[.14em] text-white">{busy?"SAVING…":purpose==="INVITATION"?"CREATE PASSWORD":"RESET PASSWORD"}</button></form></>}</section></main>;
}
